### ISSUE TITLE
Implements the WPS Groovy script parsing.

### ISSUE THREAD

**Issue by SPalominos** [orbisgis/orbisgis#843]
-  [ ] Implements the parsing of a WPS.
-  [ ]  Verify if the script is well formed.
-  [ ]  Store the process to reuse it later.
